---
- include: playbooks/common.yml
- include: playbooks/reverse_proxy.yml
- include: playbooks/web_proxy.yml
- include: playbooks/smtp_relay.yml
- include: playbooks/openldap.yml
- include: playbooks/jenkins.yml
- include: playbooks/grafana.yml
#- include: playbooks/gitea.yml
#- include: playbooks/jira.yml
- include: playbooks/rocketchat.yml
- include: playbooks/cdtportal.yml
#- include: playbooks/homepage.yml
