---
- name: restart openldap
  docker_service:
    project_name: "{{ openldap_service_name }}"
    project_src: "/tmp/{{ openldap_service_name }}"
    restarted: true
    state: present
  become: yes
  become_method: sudo
