jira_service_name: "jira"
jira_registry_url: ""   #from dockerhub
jira_image_name: "cptactionhank/atlassian-jira-software"

mariadb_version: "10.3"

jira_version: "7.12.3"
jira_user: 2
jira_group: 2

