registry_url: "docker.nexus3.devopswise.co.uk/docker-internal/"

traefik_admin_user: admin
traefik_admin_email: admin@admin.com

traefik_service_name: "traefik"

traefik_version: "latest"
traefik_ports:
  - "80:80"
  - "443:443"
  - "8080:8080"
traefik_user: 0
traefik_group: 0

