---
- name: Create a directory to store volume
  file: path="{{ item }}" state=directory mode=0777 owner="{{ gitea_user }}" group="{{ gitea_group }}"
  with_items:
    - "{{ cdt_log }}/{{ gitea_service_name }}"
    - "{{ cdt_data }}/{{ gitea_service_name }}"
    - "{{ cdt_data }}/{{ gitea_service_name }}/mysql"
    - "{{ cdt_data }}/{{ gitea_service_name }}/data"
    - "{{ cdt_data }}/{{ gitea_service_name }}/data/gitea"
    - "{{ cdt_data }}/{{ gitea_service_name }}/data/gitea/conf"
  become: yes
  become_method: sudo

- name: create directory for project_src
  file: path="/tmp/{{ gitea_service_name }}" state=directory
  become: yes
  become_method: sudo

- name: generate a random mysql password
  set_fact:
    gitea_mysql_pass: "{{ lookup('password', '../credentials/gitea_mysql_pass chars=ascii_letters,digits,hexdigits length=12') }}"

- name: sync docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /tmp/{{ gitea_service_name }}/docker-compose.yml
    mode: 0755
  become: yes
  become_method: sudo

- name: sync Dockerfile for gitea
  template:
    src: Dockerfile.j2
    dest: /tmp/{{ gitea_service_name }}/Dockerfile
    mode: 0755
  become: yes
  become_method: sudo

- name: copy wait-for-it.sh to gitea build folder
  copy:
    src: wait-for-it.sh
    dest: /tmp/{{ gitea_service_name }}/wait-for-it.sh
  become: yes
  become_method: sudo

- name: sync app.ini
  template:
    src: app.ini.j2
    dest: "{{ cdt_data }}/{{ gitea_service_name }}/data/gitea/conf/app.ini"
    mode: 0644
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
  become: yes
  become_method: sudo

- name: "Run gitea service {{ gitea_version }}"
  become: yes
  become_method: sudo
  docker_service:
    project_name: "{{ gitea_service_name }}"
    project_src: "/tmp/{{ gitea_service_name }}"
  register: output
