---
- name: restart squid
  docker_service:
    project_name: "{{ squid_service_name }}"
    project_src: "/tmp/{{ squid_service_name }}"
    restarted: true
    state: present
  become: yes
  become_method: sudo
