## new inventory

env: pro

##will load from cdt-config.json
##base_domain: __base_domain__  

cdt_protocol: https

#registry_url: "docker.nexus3.devopswise.com/docker-internal/"
registry_url: ""

docker_data: /opt/docker-data
cdt_data: /opt/cdt-data
cdt_log: /opt/cdt-log
cdt_backup: /opt/cdt-backup
cdt_cert: /opt/cdt-cert

aws_access_key: "AKIAJYUEDKFQKOPEJMHQ"
aws_region: "eu-west-1"

http_proxy_hostname: web_proxy
http_proxy_port: 3128
http_proxy: "http://{{ http_proxy_hostname }}:{{ http_proxy_port }}"
https_proxy: "{{ http_proxy }}"
no_proxy: "127.0.0.1,localhost"

#smtp configuration
smtp_relay_gmail_user: "devopswise@gmail.com"
smtp_server: "smtp.{{ base_domain }}"
smtp_domain: "mail.{{ base_domain }}"
smtp_server_port: 25

mariadb_version: "10.3"

#misc
cdt_shutdown_after_2h: false
## end of new inventory
