---
- name: Create a directory to store volume
  file: path="{{ item }}" state=directory mode=755 owner="{{ squid_user }}" group="{{ squid_group }}"
  with_items:
    - "{{ cdt_log }}/{{ squid_service_name }}"
    - "{{ cdt_data }}/{{ squid_service_name }}"
  become: yes
  become_method: sudo

- name: create directory for project_src
  file: path="/tmp/{{ squid_service_name }}" state=directory
  become: yes
  become_method: sudo

- name: sync docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /tmp/{{ squid_service_name }}/docker-compose.yml
    mode: 0755
  become: yes
  become_method: sudo

- name: sync squid3.conf
  template:
    src: squid3.conf.j2
    dest: "{{ cdt_data }}/{{ squid_service_name }}/squid3.conf"
    mode: 0755
  become: yes
  become_method: sudo

- name: "Run squid service {{ squid_version }}"
  become: yes
  become_method: sudo
  docker_service:
    project_name: "{{ squid_service_name }}"
    project_src: "/tmp/{{ squid_service_name }}"

